FROM scratch
COPY stormd /stormd
COPY miniminio /miniminio
COPY deploy/stormd-config.toml /etc/stormd/config.toml
VOLUME ["/data"]
EXPOSE 9000/tcp 9080/tcp 22/tcp
ENTRYPOINT ["/stormd"]
CMD ["--config", "/etc/stormd/config.toml"]
